# -*- coding: utf-8 -*-
"""Shared presentation constants for the graph UI."""

from ..graph_model import (
    READ, WRITE,
    CAT_GRAPHICS, CAT_COMPUTE, CAT_TRANSFER, CAT_PRESENT, CAT_SCOPE, CAT_PORTAL,
    RES_COLOR, RES_DEPTH, RES_UAV_TEX, RES_SWAPCHAIN, RES_BUFFER, RES_SAMPLED,
)

# Node geometry.
PAD = 8.0
TITLE_H = 20.0
SUBLINE_H = 18.0
BADGE_W = 26.0
BUNDLE_ROW_H = 15.0
BUNDLE_MAX_ROWS = 24
PASS_BUNDLE_ROWS_Y = 42.0
THUMB_W = 192
THUMB_H = 108
ICON_SZ = 14.0
SCOPE_STACK_OFF = (6.0, 3.0)

# Category and edge colours.
CAT_BASE_COLORS = {
    CAT_GRAPHICS: '#E53935',
    CAT_COMPUTE: '#7B1FA2',
    CAT_SCOPE: '#1976D2',
    CAT_TRANSFER: '#78909C',
    CAT_PRESENT: '#2E7D32',
    CAT_PORTAL: '#AEC0C8',
    RES_COLOR: '#C0773B',
    RES_DEPTH: '#2E3C44',
    RES_UAV_TEX: '#78909C',
    RES_SWAPCHAIN: '#F9A825',
    RES_BUFFER: '#5C6BC0',
    RES_SAMPLED: '#B0BEC5',
}

EDGE_BASE_COLORS = {
    READ: '#00897B',
    WRITE: '#d74e80',
}

# Theme colour transforms.
CANVAS_DARK_LIGHTEN = 118
CANVAS_LIGHT_DARKEN = 120
SHADOW_ALPHA_DARK = 150
SHADOW_ALPHA_LIGHT = 105
SUB_TEXT_MIX = 0.42
CATEGORY_DARK_LIGHTEN = 130
EDGE_DARK_LIGHTEN = 135
EDGE_ALPHA = 245
EDGE_MUTED_MIX = 0.58
TITLE_TINT_PASS_MIX = 0.55
TITLE_TINT_RESOURCE_MIX = 0.72
RESOURCE_BORDER_MIX = 0.5

# Edge and node visual state.
EDGE_W_BASE = 1.6
EDGE_W_DIRECT = 2.8
EDGE_W_INDIRECT = 1.5
Z_EDGE_BASE = -1.0
Z_EDGE_INDIRECT = 1.0
Z_EDGE_DIRECT = 2.0
DIM_OPACITY = 0.4
FILTER_DIM_OPACITY = 0.35
MUTED_EDGE_OPACITY = 0.9
EDGE_INDIRECT_OPACITY = 0.55
Z_NODE_BASE = 0.0
Z_NODE_HI = 3.0

# Interaction and zoom.
CLICK_SLOP = 6.0
LAYOUT_CACHE_CAP = 48
ZOOM_STEP = 1.15
ZOOM_MIN = 0.1
ZOOM_MAX = 4.0
READABLE_ZOOM = 0.8

# Text and status limits.
TOOLTIP_LIST_LIMIT = 20
TOOLTIP_EDGE_EID_LIMIT = 10
WARNING_TOOLTIP_LIMIT = 20

# Breadcrumb text.
BREADCRUMB_SEP = u' \u25b8 '
BREADCRUMB_LINK_COLOR = '#7ab0e0'
